- name: Installing python
  ansible.builtin.dnf:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Import common role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Download python dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt; pip3.6 install newrelic
  args:
    chdir: "{{app_dir}}"

- name: Copy NewRelic Config File
  ansible.builtin.template:
    src: newrelic-python.ini
    dest: /app/newrelic.ini

- name: Import SystemD
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Import Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: schema-load
  when : schema_needed

- name: Import Observability
  ansible.builtin.import_role:
    name: common
    tasks_from: observability


